name: Feature Request
description: Add an idea request for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
  - type: textarea
    id: feature-test-cases
    attributes:
      label: Test Cases
      description: Describe the test cases to do to prove that the feature works