Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/client.c File Reference
client.c File Reference
#include <poll.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "include/client.h"
#include "include/command.h"
Functions
void add_client (zappy_t *zappy, int fd)
static void add_client_data (zappy_t *zappy, int fd)
void destroy_clients (client_t *clients)
void remove_client (zappy_t *zappy, int fd)
static void remove_client_data (client_t **clients, int fd)
Function Documentation
add_client()
void add_client (zappy_t * zappy, int fd)
References add_client_data(), display_error(), and zappy.
Referenced by check_for_new_client().
add_client_data()
static void add_client_data (zappy_t * zappy, int fd) static
References append_client_out_buffer(), display_error(), and zappy.
Referenced by add_client().
destroy_clients()
void destroy_clients (client_t * clients)
References display_error().
Referenced by down_server().
remove_client()
void remove_client (zappy_t * zappy, int fd)
References display_error(), remove_client_data(), and zappy.
remove_client_data()
static void remove_client_data (client_t ** clients, int fd) static
Referenced by remove_client().