Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/command.c File Reference
command.c File Reference
#include <unistd.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stdio.h>
#include "include/command.h"
#include "include/client.h"
Functions
static char * append_client_buffer (char *buffer, char *new_buffer)
void append_client_out_buffer (client_t *client, const char *format,...)
static bool get_client_buffer (client_t *client, int fd, zappy_t *zappy)
void handle_client_command (zappy_t *zappy, int fd)
void send_client_command (zappy_t *zappy, int fd)
Function Documentation
append_client_buffer()
static char * append_client_buffer (char * buffer, char * new_buffer) static
References display_error().
Referenced by append_client_out_buffer(), and get_client_buffer().
append_client_out_buffer()
void append_client_out_buffer (client_t * client, const char * format, ...)
References append_client_buffer(), and display_error().
Referenced by add_client_data().
get_client_buffer()
static bool get_client_buffer (client_t * client, int fd, zappy_t * zappy) static
References append_client_buffer(), display_error(), execute_command(), and zappy.
Referenced by handle_client_command().
handle_client_command()
void handle_client_command (zappy_t * zappy, int fd)
References get_client_buffer(), and zappy.
Referenced by check_for_client_command().
send_client_command()
void send_client_command (zappy_t * zappy, int fd)
References display_error(), and zappy.
Referenced by check_for_client_command().