Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/exec_command.c File Reference
exec_command.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "client.h"
Functions
static void add_command (int duration, char **args, client_t *client, bool *b)
void exec_command (char **args, client_t *client, zappy_t *zappy_ptr)
static void set_upper (char **args)
Function Documentation
add_command()
static void add_command (int duration, char ** args, client_t * client, bool * b) static
Referenced by exec_command().
exec_command()
void exec_command (char ** args, client_t * client, zappy_t * zappy_ptr)
References add_command(), realloc_strcat(), and set_upper().
Referenced by process_command().
set_upper()
static void set_upper (char ** args) static
Referenced by exec_command().