Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/handle_commands.c File Reference
handle_commands.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "client.h"
#include "command.h"
Functions
static char ** allocate_args_array (int count)
static int count_tokens (char *str)
void execute_command (client_t *client, zappy_t *zappy_ptr)
static int fill_args_array (char **args, char *command, int count)
static void free_command_args (char **args)
static char ** parse_command (char *command)
static void process_command_line (client_t *client, char *command_line, zappy_t *zappy_ptr)
Function Documentation
allocate_args_array()
static char ** allocate_args_array (int count) static
Referenced by parse_command().
count_tokens()
static int count_tokens (char * str) static
Referenced by parse_command().
execute_command()
void execute_command (client_t * client, zappy_t * zappy_ptr)
References process_command_line().
Referenced by get_client_buffer().
fill_args_array()
static int fill_args_array (char ** args, char * command, int count) static
Referenced by parse_command().
free_command_args()
static void free_command_args (char ** args) static
Referenced by process_command_line().
parse_command()
static char ** parse_command (char * command) static
References allocate_args_array(), count_tokens(), and fill_args_array().
Referenced by process_command_line().
process_command_line()
static void process_command_line (client_t * client, char * command_line, zappy_t * zappy_ptr) static
References free_command_args(), parse_command(), and process_command().
Referenced by execute_command().