Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/main.c File Reference
main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <string.h>
#include <time.h>
#include <sys/types.h>
#include "include/zappy.h"
#include "include/parser.h"
#include "include/server.h"
Functions
void handle_down_server (int sig)
int main (int ac, char **av)
static void setup_down_server (void)
Variables
static zappy_t zappy = {0}
Function Documentation
handle_down_server()
void handle_down_server (int sig)
References down_server(), and zappy.
Referenced by setup_down_server().
main()
int main (int ac, char ** av)
References create_server(), down_server(), init_starting_map(), parse_arguments(), parse_str_arguments(), setup_down_server(), start_server(), and zappy.
setup_down_server()
static void setup_down_server (void) static
References handle_down_server().
Referenced by main().
Variable Documentation
zappy
zappy_t zappy = {0} static
Referenced by add_client(), add_client_data(), add_egg(), check_for_client_command(), check_for_new_client(), down_server(), get_client_buffer(), handle_client_command(), handle_down_server(), init_starting_map(), main(), remove_client(), return_egg(), send_client_command(), send_data_to_graphics(), and start_server().