Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/map.c File Reference
map.c File Reference
#include <stdlib.h>
#include "include/zappy.h"
Functions
cell_t ** create_map (parser_t *parser)
void destroy_map (cell_t **map)
static int get_total_resources (parser_t *parser, float density)
static void init_cell (cell_t *cell, int y, int x)
static coord_t * init_coord_array (parser_t *parser)
void place_resource (cell_t **map, coord_t c, int res)
static void shuffle_coords (coord_t *coords, int total_cell)
void spawn_resources (cell_t **map, parser_t *parser)
Variables
static const float densities []
Function Documentation
create_map()
cell_t ** create_map (parser_t * parser)
References display_error(), init_cell(), and spawn_resources().
Referenced by init_starting_map().
destroy_map()
void destroy_map (cell_t ** map)
Referenced by free_starting_map().
get_total_resources()
static int get_total_resources (parser_t * parser, float density) static
Referenced by spawn_resources().
init_cell()
static void init_cell (cell_t * cell, int y, int x) static
Referenced by create_map().
init_coord_array()
static coord_t * init_coord_array (parser_t * parser) static
References display_error(), and shuffle_coords().
Referenced by spawn_resources().
place_resource()
void place_resource (cell_t ** map, coord_t c, int res)
Referenced by spawn_resources().
shuffle_coords()
static void shuffle_coords (coord_t * coords, int total_cell) static
Referenced by init_coord_array().
spawn_resources()
void spawn_resources (cell_t ** map, parser_t * parser)
References densities, get_total_resources(), init_coord_array(), and place_resource().
Referenced by create_map().
Variable Documentation
densities
const float densities[] static
Initial value:
= {
    [FOOD] = 0.5f,
    [LINEMATE] = 0.3f,
    [DERAUMERE] = 0.15f,
    [SIBUR] = 0.1f,
    [MENDIANE] = 0.1f,
    [PHIRAS] = 0.08f,
    [THYSTAME] = 0.05f
}
Referenced by spawn_resources().