Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/map_creation.c File Reference
map_creation.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "include/zappy.h"
Functions
static void add_egg (starting_map_t *map, int id, const char *team_name, zappy_t *zappy)
void free_starting_map (starting_map_t *map)
starting_map_t * init_starting_map (zappy_t *zappy)
Function Documentation
add_egg()
static void add_egg (starting_map_t * map, int id, const char * team_name, zappy_t * zappy) static
References zappy.
Referenced by init_starting_map().
free_starting_map()
void free_starting_map (starting_map_t * map)
References destroy_map().
Referenced by down_server().
init_starting_map()
starting_map_t * init_starting_map (zappy_t * zappy)
References add_egg(), create_map(), and zappy.
Referenced by main().