Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/parser.c File Reference
parser.c File Reference
#include <string.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include "include/parser.h"
Functions
static int count_teams (char **av, int start, int ac)
void destroy_parser (parser_t *parser)
void display_error (const char *message)
void display_help (void)
static parser_t * init_parser (void)
parser_t * parse_arguments (int ac, char **av)
static int parse_int (char *value, int min, int max)
static char ** parse_teams (char **av, int *index, int ac, int *nb_teams)
Function Documentation
count_teams()
static int count_teams (char ** av, int start, int ac) static
References display_help().
Referenced by parse_teams().
destroy_parser()
void destroy_parser (parser_t * parser)
Referenced by down_server().
display_error()
void display_error (const char * message)
Referenced by add_client(), add_client_data(), append_client_buffer(), append_client_out_buffer(), bind_socket(), check_for_new_client(), config_socket(), create_map(), create_poll(), create_server(), create_socket(), destroy_clients(), destroy_server(), get_client_buffer(), init_coord_array(), init_parser(), init_parser_str(), listen_socket(), parse_teams(), remove_client(), send_client_command(), and start_server().
display_help()
void display_help (void)
Referenced by count_teams(), parse_arguments(), parse_int(), and parse_teams().
init_parser()
static parser_t * init_parser (void) static
References display_error().
Referenced by parse_arguments().
parse_arguments()
parser_t * parse_arguments (int ac, char ** av)
References display_help(), init_parser(), parse_int(), and parse_teams().
Referenced by main().
parse_int()
static int parse_int (char * value, int min, int max) static
References display_help().
Referenced by parse_arguments().
parse_teams()
static char ** parse_teams (char ** av, int * index, int ac, int * nb_teams) static
References count_teams(), display_error(), and display_help().
Referenced by parse_arguments().