Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/process_command.c File Reference
process_command.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "client.h"
Functions
static bool check_graphic (char **args, client_t *client, zappy_t *zappy_ptr)
static bool is_in_teams (char *get, char **teams)
static void new_connection_player (char **args, client_t *client, zappy_t *zappy_ptr)
void process_command (char **args, client_t *client, zappy_t *zappy_ptr)
char * realloc_strcat (char *dest, const char *src)
static egg_t * return_egg (zappy_t *zappy)
void send_data_to_graphics (zappy_t *zappy, char *data)
static void send_datas_new_player (client_t *client, zappy_t *zappy_ptr, egg_t *egg)
Function Documentation
check_graphic()
static bool check_graphic (char ** args, client_t * client, zappy_t * zappy_ptr) static
Referenced by process_command().
is_in_teams()
static bool is_in_teams (char * get, char ** teams) static
Referenced by process_command().
new_connection_player()
static void new_connection_player (char ** args, client_t * client, zappy_t * zappy_ptr) static
References return_egg(), and send_datas_new_player().
Referenced by process_command().
process_command()
void process_command (char ** args, client_t * client, zappy_t * zappy_ptr)
References check_graphic(), exec_command(), is_in_teams(), and new_connection_player().
Referenced by process_command_line().
realloc_strcat()
char * realloc_strcat (char * dest, const char * src)
Referenced by exec_command().
return_egg()
static egg_t * return_egg (zappy_t * zappy) static
References zappy.
Referenced by new_connection_player().
send_data_to_graphics()
void send_data_to_graphics (zappy_t * zappy, char * data)
References zappy.
Referenced by send_datas_new_player().
send_datas_new_player()
static void send_datas_new_player (client_t * client, zappy_t * zappy_ptr, egg_t * egg) static
References send_data_to_graphics().
Referenced by new_connection_player().