Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/server.c File Reference
server.c File Reference
#include <stdlib.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <poll.h>
#include "include/server.h"
#include "include/parser.h"
Functions
static void bind_socket (int server_fd, int port)
static void config_socket (int server_fd)
static struct pollfd * create_poll (int server_fd)
server_t * create_server (int port)
static int create_socket (void)
void destroy_server (server_t *server)
static void listen_socket (int server_fd)
Function Documentation
bind_socket()
static void bind_socket (int server_fd, int port) static
References display_error().
Referenced by create_server().
config_socket()
static void config_socket (int server_fd) static
References display_error().
Referenced by create_server().
create_poll()
static struct pollfd * create_poll (int server_fd) static
References display_error().
Referenced by create_server().
create_server()
server_t * create_server (int port)
References bind_socket(), config_socket(), create_poll(), create_socket(), display_error(), and listen_socket().
Referenced by main().
create_socket()
static int create_socket (void) static
References display_error().
Referenced by create_server().
destroy_server()
void destroy_server (server_t * server)
References display_error().
Referenced by down_server().
listen_socket()
static void listen_socket (int server_fd) static
References display_error().
Referenced by create_server().