Zappy API Reference: /home/matt/tek2/YEP/ZAPPY/zappy_server_src/zappy.c File Reference
zappy.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <poll.h>
#include <sys/socket.h>
#include "include/zappy.h"
#include "include/client.h"
#include "include/command.h"
Functions
static void check_for_client_command (zappy_t *zappy)
static void check_for_new_client (zappy_t *zappy)
void down_server (zappy_t *zappy)
void start_server (zappy_t *zappy)
Function Documentation
check_for_client_command()
static void check_for_client_command (zappy_t * zappy) static
References handle_client_command(), send_client_command(), and zappy.
Referenced by start_server().
check_for_new_client()
static void check_for_new_client (zappy_t * zappy) static
References add_client(), display_error(), and zappy.
Referenced by start_server().
down_server()
void down_server (zappy_t * zappy)
References destroy_clients(), destroy_parser(), destroy_parser_str(), destroy_server(), free_starting_map(), and zappy.
Referenced by handle_down_server(), and main().
start_server()
void start_server (zappy_t * zappy)
References check_for_client_command(), check_for_new_client(), display_error(), and zappy.
Referenced by main().